name: ser-bias
channels:
  - conda-forge
dependencies:
  - python=3.9
  - flake8
  - flake8-docstrings
  - pytest
  - jupyter
  - tqdm
  - numpy
  - scipy
  - matplotlib
  - pandas
  - seaborn
  - scikit-learn
  - numba
  - pydub
  - librosa
